### PR TITLE
The Snake Update

### PR DESCRIPTION
**Pull request by PhunStyle**
# The Snake Update

Preview

- Adds a !snake command for a random snake picture.
  - Also accepts !snek and !:snake:
- Also added !:cat: to !cat - emoji commands are pretty nifty on mobile.

Didn't add help and tests last time, whoops..

### CODE REVIEW

**Comment by dustinblackman** [comment]
Looks awesome! Thanks so much for this.

**Comment by insuusvenerati** [comment]
YAY \o/

**Comment by insuusvenerati** [comment]
Just tested this and it doesn't seem to work. : (

**Comment by dustinblackman** [comment]
How? Works fine.

**Comment by insuusvenerati** [comment]
Weird. I tried !snake after doing a git pull and nothing happens

**Comment by xnaas** [comment]
I did `!:snake:` and it works just fine @insuusvenerati.

**Pull request merged**
